package com.akaun.kt.sdk.models.dbschema

data class bl_del_trip_hdr(
    var acl_config: Any?,
    var acl_policy: Any?,
    var applet_guid: Any?,
    var code: String?,
    var created_by_subject_guid: String?,
    var date_created: String?,
    var date_updated: String?,
    var delivery_logic: Any?,
    var delivery_region_code: String?,
    var delivery_status: String?,
    var descr: Any?,
    var driver_name: String?,
    var guid: String?,
    var guid_driver_hdr: String?,
    var guid_region_hdr: String?,
    var guid_vehicle_hdr: String?,
    var label_list_guid: Any?,
    var module_guid: Any?,
    var name: String?,
    var namespace: Any?,
    var obj_type: Any?,
    var process_hdr_guid: Any?,
    var process_resolution_code: Any?,
    var process_resolution_guid: Any?,
    var process_status_guid: Any?,
    var process_status_name: Any?,
    var property_json: Any?,
    var revision: String?,
    var running_number_01: String?,
    var running_number_02: String?,
    var running_number_03: String?,
    var status: String?,
    var trip_end_date: String?,
    var trip_start_date: String?,
    var updated_by_subject_guid: String?,
    var vehicle_capacity: Any?,
    var vehicle_reg_plate: String?,
    var vrsn: Any?
)



