package com.akaun.kt.sdk.models.dbschema

data class bl_del_region_hdr(
    var acl_config: Any?,
    var acl_policy: Any?,
    var applet_guid: Any?,
    var code: Any?,
    var country: String?,
    var created_by_subject_guid: String?,
    var date_created: String?,
    var date_updated: String?,
    var descr: String?,
    var geofencing_json: Any?,
    var goog_polyline_complex: Any?,
    var google_location_name: String?,
    var google_location_url: String?,
    var guid: String?,
    var label_list_guid: Any?,
    var level_value: Any?,
    var module_guid: Any?,
    var name: Any?,
    var namespace: Any?,
    var obj_type: Any?,
    var property_json: Any?,
    var region: String?,
    var region_code: String?,
    var revision: String?,
    var state: String?,
    var status: String?,
    var updated_by_subject_guid: String?,
    var usage_type: String?,
    var vrsn: Any?
)