package com.akaun.kt.sdk.models.dbschema

data class bl_del_driver_hdr(
    val acl_config: Any?,
    val acl_policy: Any?,
    val addresses_json: Any?,
    val applet_guid: Any?,
    val created_by_subject_guid: String?,
    val date_created: String?,
    val date_updated: String?,
    val driver_status: String?,
    val driver_type: Any?,
    val email: String?,
    val emergency_name: String?,
    val emergency_phone_number: String?,
    val guid: String?,
    val id_no: String?,
    val join_date: String?,
    val license_no: String?,
    val login_subject_guid: String?,
    val module_guid: Any?,
    val name: String?,
    val namespace: Any?,
    val obj_type: Any?,
    val phone_number: String?,
    val property_json: Any?,
    val relationship: String?,
    val remarks: Any?,
    val revision: String?,
    val status: String?,
    val updated_by_subject_guid: String?,
    val vrsn: Any?
)