package com.akaun.kt.sdk.models.dbschema

data class bl_del_job_shipment_link(
    val acl_config: String? = null,
    val acl_policy: String? = null,
    val applet_guid: Any? = null,
    val collection_amount: Any? = null,
    val created_by_subject_guid: String? = null,
    val created_date: String? = null,
    val delivery_logic: Any? = null,
    val delivery_status: String? = null,
    val fi_item_hdr_guid: Any? = null,
    val guid: String? = null,
    val installation_duration_minute: Any? = null,
    val inv_item_hdr_guid: Any? = null,
    val item_code: Any? = null,
    val item_name: String? = null,
    val job_hdr_guid: String? = null,
    val module_guid: Any? = null,
    val namespace: Any? = null,
    val obj_type: Any? = null,
    val process_hdr_guid: Any? = null,
    val process_resolution_code: Any? = null,
    val process_resolution_guid: Any? = null,
    val process_status_guid: Any? = null,
    val process_status_name: Any? = null,
    val proof_of_received: Any? = null,
    val proof_rct_id: Any? = null,
    val proof_rct_name: Any? = null,
    val proof_rct_phone: Any? = null,
    val proof_rct_remarks: Any? = null,
    val property_json: String? = null,
    val qty_delivered: Any? = null,
    val qty_to_deliver: Any? = null,
    val quantity: Double? = null,
    val reason: Any? = null,
    val recipient_contact: Any? = null,
    val recipient_id: String? = null,
    val recipient_name: String? = null,
    val revision: String? = null,
    val server_doc_1: String? = null,
    val server_doc_2: Any? = null,
    val server_doc_3: Any? = null,
    val server_doc_4: Any? = null,
    val server_doc_5: Any? = null,
    val shipment_hdr_guid: String? = null,
    val status: String? = null,
    val updated_by_subject_guid: String,
    val updated_date: String? = null,
    val vrsn: Any? = null
)