package com.akaun.kt.app.delivery.driverapp.model.trip

data class bl_del_trip_hdr(
    val acl_config: Any?,
    val acl_policy: Any?,
    val applet_guid: Any?,
    val code: String?,
    val created_by_subject_guid: String?,
    val date_created: String?,
    val date_updated: String?,
    val delivery_logic: Any?,
    val delivery_region_code: String?,
    val delivery_status: String?,
    val descr: Any?,
    val driver_name: String?,
    val guid: String?,
    val guid_driver_hdr: String?,
    val guid_region_hdr: String?,
    val guid_vehicle_hdr: String?,
    val label_list_guid: Any?,
    val module_guid: Any?,
    val name: String?,
    val namespace: Any?,
    val obj_type: Any?,
    val process_hdr_guid: Any?,
    val process_resolution_code: Any?,
    val process_resolution_guid: Any?,
    val process_status_guid: Any?,
    val process_status_name: Any?,
    val property_json: Any?,
    val revision: String?,
    val running_number_01: Int?,
    val running_number_02: Int?,
    val running_number_03: Int?,
    val status: String?,
    val trip_end_date: String?,
    val trip_start_date: String?,
    val updated_by_subject_guid: String?,
    val vehicle_capacity: Any?,
    val vehicle_reg_plate: String?,
    val vrsn: Any?
)



