package com.akaun.kt.sdk.models.dbschema

data class bl_del_job_ext(
    var acl_config: Any? = null,
    var acl_policy: Any? = null,
    var applet_guid: Any? = null,
    var created_by_subject_guid: Any? = null,
    var created_date: String? = null,
    var dochdr_link_guid: Any? = null,
    var docline_link_guid: Any? = null,
    var ext_code: Any? = null,
    var ext_option: Any? = null,
    var ext_type: Any? = null,
    var guid: String? = null,
    var hdr_guid: String? = null,
    var module_guid: Any? = null,
    var namespace: Any? = null,
    var obj_type: Any? = null,
    var param_code: String? = null,
    var param_name: String? = null,
    var param_option_json: Any? = null,
    var param_type: String? = null,
    var property_json: Any? = null,
    var revision: String? = null,
    var status: String? = null,
    var updated_by_subject_guid: Any? = null,
    var updated_date: String? = null,
    var value_datetime: Any? = null,
    var value_file: Any? = null,
    var value_json: Any? = null,
    var value_numeric: Any? = null,
    var value_string: String? = null,
    var vrsn: Any? = null
)