package com.akaun.kt.sdk.models.dbschema


data class bl_del_job_docline_link(
    var guid: String? = null,
    var guid_doc_hdr: String? = null,
    var namespace: String? = null,
    var module_guid: String? = null,
    var applet_guid: String? = null,
    var guid_generic_doc_line: String? = null,
    var guid_job_hdr: String? = null,
    var guid_dochdr_link: String? = null,
    var guid_inv_item_hdr: String? = null,
    var guid_fi_item_hdr: String? = null,
    var item_code: String? = null,
    var item_name: String? = null,
    var recipient_name: String? = null,
    var id_recipient: String? = null,
    var recipient_contact: String? = null,
    var proof_of_received: String? = null,
    var quantity: String? = null,
    var qty_to_deliver: String? = null,
    var qty_delivered: String? = null,
    var installation_duration_minute: String? = null,
    var delivery_status: String? = null,
    var delivery_logic: String? = null,
    var process_hdr_guid: String? = null,
    var process_status_guid: String? = null,
    var process_status_name: String? = null,
    var process_resolution_guid: String? = null,
    var process_resolution_code: String? = null,
    var obj_type: String? = null,
    var status: String? = null,
    var revision: String? = null,
    var vrsn: String? = null,
    var created_date: String? = null,
    var updated_date: String? = null,
    var created_by_subject_guid: String? = null,
    var updated_by_subject_guid: String? = null,
    var pkg_no_of_parts: String? = null,
    var proof_rct_name: String? = null,
    var proof_rct_id: String? = null,
    var proof_rct_phone: String? = null,
    var proof_rct_remarks: String? = null,
    var collection_amount: String? = null,
    var reason: String? = null,
    var item_type: String? = null,
    var item_subtype: String? = null,
    var sales_invoice_hdr_guid: String? = null,
    var sales_invoice_line_guid: String? = null,
    var sales_invoice_process_status: String? = null,
    var serial_no_json: Any? = null,
    var batch_no_json: Any? = null,
    var bin_no_json: Any? = null
)