package com.akaun.kt.app.delivery.driverapp.model.job

data class bl_del_job_ext(
    val acl_config: AclConfig? = null,
    val acl_policy: AclPolicy? = null,
    val applet_guid: Any? = null,
    val created_by_subject_guid: Any? = null,
    val created_date: String? = null,
    val dochdr_link_guid: Any? = null,
    val docline_link_guid: Any? = null,
    val ext_code: Any? = null,
    val ext_option: Any? = null,
    val ext_type: Any? = null,
    val guid: String? = null,
    val hdr_guid: String? = null,
    val module_guid: Any? = null,
    val namespace: Any? = null,
    val obj_type: Any? = null,
    val param_code: String? = null,
    val param_name: String? = null,
    val param_option_json: String? = null,
    val param_type: String? = null,
    val property_json: String? = null,
    val revision: String? = null,
    val status: String? = null,
    val updated_by_subject_guid: Any? = null,
    val updated_date: String? = null,
    val value_datetime: Any? = null,
    val value_file: Any? = null,
    val value_json: String? = null,
    val value_numeric: Any? = null,
    val value_string: String? = null,
    val vrsn: Any? = null
)