package com.akaun.kt.sdk.models.dbschema

import com.akaun.kt.sdk.models.dbschema.intermediate.LogJson

data class bl_fi_generic_doc_link(
    var acl_config: Any? = null,
    var acl_policy: Any? = null,
    var amount_contra: Any? = null,
    var amount_signum: Any? = null,
    var applet_guid: Any? = null,
    var batch_no: Any? = null,
    var bin_no: Any? = null,
    var client_doc_status_01: Any? = null,
    var client_doc_status_02: Any? = null,
    var client_doc_status_03: Any? = null,
    var client_doc_status_04: Any? = null,
    var client_doc_status_05: Any? = null,
    var created_by_subject_guid: String? = null,
    var created_date: String? = null,
    var date_doc_1_hdr: Any? = null,
    var date_doc_1_line: Any? = null,
    var date_doc_2_hdr: Any? = null,
    var date_doc_2_line: Any? = null,
    var date_txn: String? = null,
    var descr: String? = null,
    var guid: String? = null,
    var guid_doc_1_hdr: String? = null,
    var guid_doc_1_line: String? = null,
    var guid_doc_2_hdr: String? = null,
    var guid_doc_2_line: String? = null,
    var guid_doc_event: Any? = null,
    var log_json: LogJson? = null,
    var logic: Any? = null,
    var module_guid: Any? = null,
    var namespace: Any? = null,
    var option: Any? = null,
    var property_json: Any? = null,
    var quantity_contra: Double? = null,
    var quantity_signum: Double? = null,
    var remarks: Any? = null,
    var revision: String? = null,
    var serial_no: Any? = null,
    var server_doc_type_doc_1_hdr: String? = null,
    var server_doc_type_doc_1_line: String? = null,
    var server_doc_type_doc_2_hdr: String? = null,
    var server_doc_type_doc_2_line: String? = null,
    var status: String? = null,
    var txn_type: String? = null,
    var updated_by_subject_guid: String? = null,
    var updated_date: String? = null,
    var vrsn: Any? = null
)
