package com.akaun.kt.sdk.models.dbschema

import com.akaun.kt.sdk.models.dbschema.intermediate.LogJson
import com.akaun.kt.sdk.models.dbschema.intermediate.PropertyJson

data class bl_fi_mst_comp(
    var abbreviation: String? = null,
    var addressLine1: String? = null,
    var addressLine2: String? = null,
    var addressLine3: String? = null,
    var addressLine4: String? = null,
    var addressLine5: String? = null,
    var ccyCode: String? = null,
    var chartOfAccGuid: String? = null,
    var city: String? = null,
    var clientKey: String? = null,
    var clientSource: String? = null,
    var clientValue: String? = null,
    var code: String? = null,
    var compRef1: String? = null,
    var compRef2: String? = null,
    var compRef3: String? = null,
    var compRegistrationNum: String? = null,
    var compTimeZone: String? = null,
    var country: String? = null,
    var createdBySubjectGuid: String? = null,
    var createdDate: String? = null,
    var defaultTaxCodeInput: String? = null,
    var defaultTaxCodeOutput: String? = null,
    var descr: String? = null,
    var email: String? = null,
    var entityHdrGuid: String? = null,
    var geolocLatitude: String? = null,
    var geolocLongitude: String? = null,
    var guid: String? = null,
    var logJson: Any? = null,
    var modifiedBySubjectGuid: String? = null,
    var modifiedDate: String? = null,
    var name: String? = null,
    var phone: String? = null,
    var postalCode: String? = null,
    var propertyJson: Any? = null,
    var revision: String? = null,
    var sstRegistrationId: String? = null,
    var state: String? = null,
    var status: String? = null,
    var taxInclusiveInput: Boolean? = null,
    var taxInclusiveOutput: Boolean? = null,
    var taxRegistrationId: String? = null,
    var vrsn: String? = null,
    var websiteUrl: String? = null
)